name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checks out your repository code

      - name: Install Firebase CLI
        run: npm install -g firebase-tools  # Installs Firebase CLI globally

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0.6-alpha
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}  # Firebase service account JSON
          projectId: flowtasks-62ed6  # Your Firebase project ID
          expires: 7d  # Optional, default is 7 days for preview channels
